### ISSUE TITLE
更新出错提示未除

### ISSUE THREAD

**Issue by cn0068** [shuax/edge_plus#1]
Microsoft Edge
版本 102.0.1212.0 (正式版本) (64 位)
检查更新时出错: 无法创建该组件(错误代码 1: [0x80004005](https://go.microsoft.com/fwlink/?linkid=2068169&0x80004005))。
[了解更多信息](https://go.microsoft.com/fwlink/?linkid=2068169)
通过按流量计费的连接下载更新
通过按流量计费的网络(例如手机网络)自动下载更新，并在浏览器重新启动时应用更新。可能会收费。

**Comment by shuax** [comment]
这个软件是设计给原版用的，所以不需要去除。
