### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by jiaxing0714** [shuax/edge_plus#10]
浏览器  edge  
能否增加个 把剪切板中的网址。在新标签打开。
edge 自带的快捷键   ctrl+t (新建一页) ctrl+shift+L 粘贴并访问。
能不能想办法让他快速实现。比如。右键点标签页+号   双击啦。

**Comment by shuax** [comment]
建议用鼠标手势 https://shuax.com/project/mouseinc/

画一个S就能实现你说的效果
