### ISSUE TITLE
edge 102.0.1233.0 版本中失效

### ISSUE THREAD

**Issue by jErRy-YaN-0** [shuax/edge_plus#11]
启动 msedge.exe 后崩溃退出。上一版 102.0.1227.0 中没有问题。应该是ms修改了主程序。

**Comment by jErRy-YaN-0** [comment]
另：期待能够恢复用户数据的“便携”功能（保存在当前目录中）

**Comment by shuax** [comment]
等正式版再说，另外这是给原版用的，不搞便携
