### ISSUE TITLE
可以给【关闭其它标签页】和【关闭右侧标签页】配置上快捷键吗？

### ISSUE THREAD

**Issue by heartotichMT** [shuax/edge_plus#12]
edge好像不能通过快捷键来实现 快速【关闭其它标签页】和【关闭右侧标签页】，这两个功能经常用到

**Comment by shuax** [comment]
这个应该装个扩展就能搞定。

**Comment by heartotichMT** [comment]
> 
谢谢，花了些时间重新在微软拓展商店里找到了可以配置这些快捷键的拓展了
