### ISSUE TITLE
目前新版edge已经支持双击关闭标签页了

### ISSUE THREAD

**Issue by Mixlining** [shuax/edge_plus#24]
详情见【微软 Win11/10 Edge 浏览器“双击关闭标签页”功能正式上线】https://www.ithome.com/0/635/200.htm
不知道是否会冲突

**Comment by masktao** [comment]
+最新版的edge在辅助选项没有双击开关, 然而自带的双击效果有点缓慢

**Comment by 754932057** [comment]
很奇怪，我的edge浏览器最新版居然没有双击关闭标签页这个选项

**Comment by csanmm887123** [comment]
奇葩的微软，最新版的又给取消了，这个作者的插件很好用
