### ISSUE TITLE
使用扩展作为标签页或者单独打开扩展 双击关闭标签页 会退出浏览器

### ISSUE THREAD

**Issue by MetaUoa** [shuax/edge_plus#3]
1.只打开扩展页面 双击会关闭浏览器
1.1打开扩展页面 再新建1个标签页 双击也会关闭浏览器
1.2打开扩展页面 再新建2个标签页 双击会保留至一个新标签页

2.使用 MONKNOW 新标签页 双击会关闭浏览器--发现和打开扩展一样的情况

不知道算BUG不

**Comment by shuax** [comment]
试了下，应该是bug

**Comment by INTERlinux** [comment]
> 试了下，应该是bug

如果打开的标签无法加载或者正在加载时，双击也会关闭和它相邻的标签

**Comment by shuax** [comment]
新版应该修复了

**Comment by MetaUoa** [comment]
> 新版应该修复了

测试问题解决，感谢
