### ISSUE TITLE
单文件放到目录里为什么不起作用呢

### ISSUE THREAD

**Issue by Lyn6969** [shuax/edge_plus#5]
如题
![image](https://user-images.githubusercontent.com/42564665/162117523-eb019bd2-61eb-420b-ae05-3aac42be1c24.png)

**Comment by shuax** [comment]
![-748cd3258ffbc03e](https://user-images.githubusercontent.com/6940583/162118072-ad85f1da-eb3f-4d0b-8619-21f747a58652.jpg)

**Comment by Lyn6969** [comment]
> ![-748cd3258ffbc03e](https://user-images.githubusercontent.com/6940583/162118072-ad85f1da-eb3f-4d0b-8619-21f747a58652.jpg)
🤣🤣🤣🤣🤣好吧，谢谢

**Comment by Lyn6969** [comment]
> @Lyn6969 你放置的目录不对，应该直接放置到 `Applications` 那一层目录。我自己使用的是 **Microsoft Edge Beta** ，确认插件可用。
> 
> ```
> C:\Program Files (x86)\Microsoft\Edge Beta\Application\KBDUS.dll
> ```
> 
> 话说 @shuax 不考虑改进一下 `.github/workflows/build.yml` ，将 `KBDUS.dll` 直接发布到 GitHub Releases 中嘛？比如使用 [softprops/action-gh-release](https://github.com/marketplace/actions/gh-release) ？

好的谢谢，我试一下！

**Comment by Lyn6969** [comment]
> @Lyn6969 你放置的目录不对，应该直接放置到 `Applications` 那一层目录。我自己使用的是 **Microsoft Edge Beta** ，确认插件可用。
> 
> ```
> C:\Program Files (x86)\Microsoft\Edge Beta\Application\KBDUS.dll
> ```
> 
> 话说 @shuax 不考虑改进一下 `.github/workflows/build.yml` ，将 `KBDUS.dll` 直接发布到 GitHub Releases 中嘛？比如使用 [softprops/action-gh-release](https://github.com/marketplace/actions/gh-release) ？

![image](https://user-images.githubusercontent.com/42564665/162181164-f73635f4-048b-423d-bc28-f13037deb95b.png)
好像还是不太行

**Comment by Dragon1573** [comment]
> 好像还是不太行

你的 Edge 重启了吗？经确认， `README.md` 中4个功能都是可用的，『保留最后标签页』的效果相当于执行 `Alt + Home` 。

**Comment by Lyn6969** [comment]
> > 好像还是不太行
> 
> 你的 Edge 重启了吗？经确认， `README.md` 中4个功能都是可用的，『保留最后标签页』的效果相当于执行 `Alt + Home` 。

重启了呢，我还以为是因为我用的垂直标签栏的缘故，我切换回来也是不可用的

**Comment by Dragon1573** [comment]
我也切换到了垂直标签栏模式，还是可以正常使用的。

![1649332311031](https://user-images.githubusercontent.com/49941141/162193350-d6b61aae-cda1-44ec-8a23-5cd5c4792aed.gif)

也有可能是你下载的版本不匹配？ Artifacts 里有两个版本（ `windows-x64` 和 `windows-x86` ）

**Comment by Lyn6969** [comment]
> 我也切换到了垂直标签栏模式，还是可以正常使用的。
> 
> ![1649332311031](https://user-images.githubusercontent.com/49941141/162193350-d6b61aae-cda1-44ec-8a23-5cd5c4792aed.gif)
> 
> 也有可能是你下载的版本不匹配？ Artifacts 里有两个版本（ `windows-x64` 和 `windows-x86` ）

现在应该都是64位吧，我试了一下32位的，好像也不行。

**Comment by shuax** [comment]
我觉得还有种可能就是安全软件拦截了。

**Comment by Dragon1573** [comment]
> 我觉得还有种可能就是安全软件拦截了。

@Lyn6969 我目前使用的系统是 **Windows 11 专业版** ，安全工具是 **火绒** ，基本上全默认设置。实操安装过程中并没有出现拦截行为弹窗。

**Comment by Lyn6969** [comment]
> 

我跟你一模一样

**Comment by Lyn6969** [comment]
> > 我觉得还有种可能就是安全软件拦截了。
> 
> @Lyn6969 我目前使用的系统是 **Windows 11 专业版** ，安全工具是 **火绒** ，基本上全默认设置。实操安装过程中并没有出现拦截行为弹窗。

我和你一模一样
