### ISSUE TITLE
[Bug] Edge Beta 标签栏失效

### ISSUE THREAD

**Issue by Dragon1573** [shuax/edge_plus#7]
## 💻 软件环境

- 操作系统： **Windows 11 专业版 21H2 (22000.593)**
- 浏览器： **Microsoft Edge 101.0.1210.10 (正式版本) beta (64 位)**
- 插件版本：
  - 提交记录： https://github.com/shuax/edge_plus/commit/83588b396e441042626629daf437128697994247
  - GitHub Workflows 流水线号： [`build #1`](https://github.com/shuax/edge_plus/actions/runs/2052888620)
  - Artifacts 构件编号： [`5829480289-195627545`](https://github.com/shuax/edge_plus/suites/5829480289/artifacts/195627545)

## ❓ 简述

在 Edge Beta 中以全屏模式播放视频（ [`BV1W44y1q7Tq`](https://www.bilibili.com/video/BV1W44y1q7Tq) ，播放策略 `AV1` ），较长时间后使用 `Esc` 退出全屏模式。顶部标签栏消失，仅『新标签页』按钮存在。

![image](https://user-images.githubusercontent.com/49941141/162627868-930715eb-16f9-4a30-8652-a45b0028ba92.png)

点击按钮，或从外部打开新链接，标签栏恢复正常。

![image](https://user-images.githubusercontent.com/49941141/162628397-139565e9-f06d-4ce3-ae38-6255ffd0cca2.png)

**Comment by shuax** [comment]
和[edge_plus](https://github.com/shuax/edge_plus)有关系吗？

**Comment by Dragon1573** [comment]
没有安装插件之前未曾出现过这个现象，目前已经更新到如下版本，等下午再试试：

- 提交记录： https://github.com/shuax/edge_plus/commit/2b9a42c42ed62bb7132672d33779314b0202c442
- 流水线编号： [build #3](https://github.com/shuax/edge_plus/actions/runs/2115650860)
- 编译产物号： [5988478537-206415814](https://github.com/shuax/edge_plus/suites/5988478537/artifacts/206415814)

**Comment by Dragon1573** [comment]
1. `build #3` 暂时没能复现此问题；
2. 已卸载 `edge_plus` 插件；
3. 偶然复现问题：
   
![image](https://user-images.githubusercontent.com/49941141/162716426-43716611-e0aa-4e5e-8148-3ab12acab03e.png)

![image](https://user-images.githubusercontent.com/49941141/162716479-f4ddabd5-f083-41db-bde6-b85de16f1cc7.png)

*****

或许是 Edge Beta 自身的问题？准备切换到 Edge Core 再试试。
