### ISSUE TITLE
请求提供一个自定义开启/关闭某个的选项

### ISSUE THREAD

**Issue by FISHandCHEAP** [shuax/edge_plus#8]
比如说，我想要在关闭这两个功能的同时

> 鼠标悬停标签栏滚动
> 按住右键时滚轮滚动标签栏

保留这两个功能开启

> 双击关闭标签页
> 保留最后标签页（防止关闭最后一个标签页时关闭浏览器，点X不行）

用注册表或者同目录下的ini文件进行配置都可以的呀

**Comment by shuax** [comment]
fork了改代码吧

**Comment by FISHandCHEAP** [comment]
好的！
